// Konya İlçeleri
export const KONYA_DISTRICTS = [
  'Ahırlı',
  'Akören',
  'Akşehir',
  'Altınekin',
  'Beyşehir',
  'Bozkır',
  'Cihanbeyli',
  'Çeltik',
  'Çumra',
  'Derbent',
  'Derebucak',
  'Doğanhisar',
  'Emirgazi',
  'Ereğli',
  'Güneysınır',
  'Hadim',
  'Halkapınar',
  'Hüyük',
  'Ilgın',
  'Kadınhanı',
  'Karapınar',
  'Karatay',
  'Kulu',
  'Meram',
  'Sarayönü',
  'Selçuklu',
  'Seydişehir',
  'Taşkent',
  'Tuzlukçu',
  'Yalıhüyük',
  'Yunak',
] as const;

export type KonyaDistrict = typeof KONYA_DISTRICTS[number];
